# Generated by Django 6.0.3 on 2026-03-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_alter_plant_plant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
