# Generated by Django 6.0.3 on 2026-03-25 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_addtocart'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='booking',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 30, 3, 50, 57, 317935)),
        ),
        migrations.AddField(
            model_name='booking',
            name='district',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='first_name',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='last_name',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='pay_method',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='pincode',
            field=models.CharField(default='000000', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='state',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='contact',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
