# Generated by Django 6.0.3 on 2026-03-25 22:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_booking_address_booking_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 30, 4, 16, 49, 793335)),
        ),
    ]
